[server]
port = 8501
maxUploadSize = 500
enableXsrfProtection = false
enableCORS = false
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0284C7"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"
