# ==============================================================================
# Streamlit Secrets Configuration - WCL GEMOY
# Anda dapat menambahkan, menghapus, atau mengubah username & password di sini.
# ==============================================================================

[passwords]
admin = "wclgemoy2026"
optim = "ioh2026"
engineer = "nr26gemoy"
